version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  install-node:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: 
          command: yarn build
          name: Run yarn build
workflows:
  install-node:
    jobs:
      - install-node
  build:
    jobs:
      - node/run:
          yarn-run: build